---
kind: pipeline
type: docker
name: build-apps

environment:
  IMAGE_NAME: "ghcr.io/bramanda48/nestjs-clean-code"

steps:
  - name: build apps
    image: node:16-alpine
    commands:
      - 'echo -e "+ BRANCH SOURCE: $DRONE_SOURCE_BRANCH\n+ BRANCH TARGET: $DRONE_TARGET_BRANCH";'
      - yarn install
      - yarn build
    when:
      event:
        - push
        - pull_request

  - name: run testing
    image: node:16-alpine
    commands:
      - yarn test
    when:
      event:
        - push
        - pull_request

  - name: build docker image
    image: docker:dind
    commands:
      - 'echo -e "+ BRANCH SOURCE: $DRONE_SOURCE_BRANCH\n+ BRANCH TARGET: $DRONE_TARGET_BRANCH";'
      - export BUILD_AT="$(TZ=":Asia/Jakarta" date '+%Y-%m-%dT%H:%M:%S') (GMT+7)";
      - export BUILD_VERSION="$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)";
      - docker build
        -f Dockerfile.droneci
        -t "$IMAGE_NAME:$DRONE_TARGET_BRANCH"
        --build-arg REPOSITORY_URL="$DRONE_REPO_LINK"
        --build-arg BUILD_AT="$BUILD_AT"
        --build-arg BUILD_VERSION="$BUILD_VERSION"
        --build-arg BUILD_NUMBER="$DRONE_BUILD_NUMBER"
        --build-arg BRANCH_NAME="$DRONE_TARGET_BRANCH"
        --build-arg BRANCH_COMMIT_SHA="$DRONE_COMMIT_SHA"
        --build-arg BRANCH_COMMIT_MESSAGE="$DRONE_COMMIT_MESSAGE" .
      - docker tag "$IMAGE_NAME:$DRONE_TARGET_BRANCH" "$IMAGE_NAME:$BUILD_VERSION-build.$DRONE_BUILD_NUMBER"
      - docker images
    volumes:
      - name: dockersock
        path: /var/run
    when:
      event:
        - push

  - name: login and upload image to ghcr.io
    image: docker:dind
    commands:
      - docker images
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin ghcr.io
      - docker push --all-tags "$IMAGE_NAME"
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_REGISTRY_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD
    when:
      event:
        - push

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - develop

---
kind: pipeline
type: docker
name: promote-image

environment:
  IMAGE_NAME: "ghcr.io/bramanda48/nestjs-clean-code"

steps:
  - name: create new docker tags and upload it
    image: docker:dind
    commands:
      - sleep 5
      - 'echo -e "+ BRANCH SOURCE: $DRONE_SOURCE_BRANCH\n+ BRANCH TARGET: $DRONE_TARGET_BRANCH";'
      - export BUILD_VERSION="$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)";
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin ghcr.io
      - docker pull "$IMAGE_NAME:$DRONE_SOURCE_BRANCH"
      - docker tag  "$IMAGE_NAME:$DRONE_SOURCE_BRANCH" "$IMAGE_NAME:$DRONE_TARGET_BRANCH"
      - docker tag  "$IMAGE_NAME:$DRONE_SOURCE_BRANCH" "$IMAGE_NAME:$BUILD_VERSION-build.$DRONE_BUILD_NUMBER"
      - docker images
      - docker push "$IMAGE_NAME:$DRONE_TARGET_BRANCH"
      - docker push "$IMAGE_NAME:$BUILD_VERSION-build.$DRONE_BUILD_NUMBER"
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_REGISTRY_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD

  - name: relase new version in repository
    image: docker:dind
    commands:
      - echo "";
    when:
      branch:
        - master
        - main

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  event:
    - push
  branch:
    - staging
    - master
    - main

---
kind: pipeline
type: docker
name: deploy-apps

environment:
  IMAGE_NAME: "ghcr.io/bramanda48/nestjs-clean-code"

steps:
  - name: get requested image
    image: docker:dind
    commands:
      - sleep 5
      - export BUILD_VERSION="$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)";
      - export IMAGE_TAG="$([[ ! -z "$DRONE_BUILD_PARENT" && "$DRONE_BUILD_PARENT" -gt 0 ]] && echo "$BUILD_VERSION-build.$DRONE_BUILD_PARENT" || echo "$DRONE_SOURCE_BRANCH")";
      - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USERNAME --password-stdin ghcr.io
      - docker pull "$IMAGE_NAME:$IMAGE_TAG"
      - docker images
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_REGISTRY_USERNAME:
        from_secret: DOCKER_REGISTRY_USERNAME
      DOCKER_REGISTRY_PASSWORD:
        from_secret: DOCKER_REGISTRY_PASSWORD

  - name: deploying apps to production server
    image: docker:dind
    commands:
      - 'echo "TARGET ENVIRONMENT: $DRONE_DEPLOY_TO"'
    when:
      event:
        - push
        - promote
      target:
        - production
      branch:
        - master
        - main

  - name: deploying apps to staging server
    image: docker:dind
    commands:
      - 'echo "TARGET ENVIRONMENT: $DRONE_DEPLOY_TO"'
    when:
      event:
        - push
        - promote
      target:
        - staging
      branch:
        - staging

  - name: deploying apps to development server
    image: docker:dind
    commands:
      - 'echo "TARGET ENVIRONMENT: $DRONE_DEPLOY_TO"'
    when:
      event:
        - push
        - promote
      target:
        - development
      branch:
        - develop

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  event:
    - push
    - promote
  branch:
    - develop
    - staging
    - master
    - main
